### ISSUE TITLE
Don't see anything..

### ISSUE THREAD

**Issue by samdakap** [julien-nc/integration_openai#1]
Hi, 
could you please describe how to use the plugin, please?
I put the API key already, but I don't see any context menu anywhere, or anything.
Where are we supposed to provide input?
Thanks.

**Comment by julien-nc** [comment]
Hi. Thanks for the interest. This app adds a "smart picker" provider which is new in Nextcloud 26. This picker can be used in Talk, Text, the Mail composer and some other places. In Talk and Text, it should appear when you type "/". In Text and Mail's composer, there is a context menu action to open it.

There have been some last minute issues with frontend library compatibility. The picker might not work perfectly in Text. It will completely be solved by NC 26 RC2.

I'm interested by your feedback.
Which version of Nextcloud are you running? RC1, master branch?

**Comment by Mer0me** [comment]
Can't find the context menu in mail.
On Talk, the image generation only paste a big link to the image, no preview :(

**Comment by julien-nc** [comment]
An internal link is now returned by the Dall-e provider. This makes it possible to have link previews.
@Mer0me Could you try [v1.0.3-1-nightly](https://github.com/julien-nc/integration_openai/releases/download/v1.0.3-1-nightly/integration_openai-1.0.3-1-nightly.tar.gz)?
Otherwise this will be included in v1.0.3.

**Comment by CesiumCs** [comment]
Could some of this extra explanation end up in the readme so people don't have to look through closed issues for an idea on what it does? Some people (me) might not understand what a link picker is.
