### ISSUE TITLE
OpenAI model configuration

### ISSUE THREAD

**Issue by Dual-0** [julien-nc/integration_openai#2]
Hello,

I notice that the used `text-davinci-003` model is [hardcoded](https://github.com/julien-nc/integration_openai/blob/7f09a8eaf050c4396d6869230a3fdce2ee95cffc/lib/AppInfo/Application.php#L26). It would be great to make the model configurable. 

As shown in the [OpenAI Blog ](https://openai.com/blog/introducing-chatgpt-and-whisper-apis) we could use the cheaper ChatGPT model:
> The ChatGPT model family we are releasing today, gpt-3.5-turbo, is the same model used in the ChatGPT product. It is priced at $0.002 per 1k tokens, which is 10x cheaper than our existing GPT-3.5 models. It’s also our best model for many non-chat use cases—we’ve seen early testers migrate from text-davinci-003 to gpt-3.5-turbo with only a small amount of adjustment needed to their prompts.

All available models are shown [here](https://platform.openai.com/docs/models).

Thanks in advance

**Comment by julien-nc** [comment]
Hi, the model is not hardcoded. If you're referring to https://github.com/julien-nc/integration_openai/blob/main/lib/AppInfo/Application.php#L26 it is just the default selected one.

If you expand the "Advanced options" in the picker modal, you'll see a model selector. The model list is obtained from the OpenAI API. This list includes `gpt-3.5-turbo`. Problem is that this model can't be used with the API endpoint currently used by this app. I'll check if it's possible to adjust the endpoint depending on the selected model.

**Comment by Dual-0** [comment]
Hi, sorry I missed this. found the "Advanced options". Wouldn't it be good if you can set the default model in the admin section? Thanks for investigation because of the `gpt-3.5-turbo` model.

**Comment by julien-nc** [comment]
So the API must be used a bit differently with GPT models. It is now supported by this integration app.
There's also a new admin setting to set the global default completion model.
Also, the last used model is preselected when reopening the picker (this is user specific). This superseeds the global default.

Could you try [v1.0.3-2-nightly](https://github.com/julien-nc/integration_openai/releases/download/v1.0.3-2-nightly/integration_openai-1.0.3-2-nightly.tar.gz)?

**Comment by Dual-0** [comment]
ohh that was quiet fast! [v1.0.3-2-nightly](https://github.com/julien-nc/integration_openai/releases/download/v1.0.3-2-nightly/integration_openai-1.0.3-2-nightly.tar.gz) is working very well.

Admin-Panel:
![image](https://user-images.githubusercontent.com/37346547/227730157-135a96a7-f5db-4c67-a9cb-e7173eaffc55.png)

Integration in Notes App:
![image](https://user-images.githubusercontent.com/37346547/227730427-2faf7304-e168-4935-b176-5fd4a94c175c.png)

Text in Notes App:
![image](https://user-images.githubusercontent.com/37346547/227730445-f3622b66-950b-40d7-a050-68942e126597.png)

thanks for the quick implementation!

**Comment by julien-nc** [comment]
Thanks, that was a quick test as well!

Could you check the new image generation system is also working well? It used to return the direct link to the generated image. It now returns an internal link which has a preview.

**Comment by Dual-0** [comment]
When I changed the model in the admin-section and switch to the notes app the model under "advanced options" is still `gpt-3.5-turbo`. I think the notes app remember the last used model. Is this a bug or a feature?

Part 2: Dall-E is working well too.

![image](https://user-images.githubusercontent.com/37346547/227731157-b83f8691-e428-46a2-9806-d6be3d93772c.png)

Result:

![image](https://user-images.githubusercontent.com/37346547/227731180-239be7c5-6253-4268-8b3f-64ef69b04a09.png)

P.S.: where does the app save the pictures?

**Comment by julien-nc** [comment]
> When I changed the model in the admin-section and switch to the notes app the model under "advanced options" is still gpt-3.5-turbo. I think the notes app remember the last used model. Is this a bug or a feature?

Like i said:

> Also, the last used model is preselected when reopening the picker (this is user specific). This superseeds the global default.

Which means, the default model for a user who never used the picker is the one selected by the admin. But after it has been used once, the user's default model is the last used one.

> where does the app save the pictures?

Thanks a lot for testing this :blue_heart:. The magic is that NC does not save the pictures. Only the "real" URL to the image is saved in NC's database. The internal links `https://blabla.org/apps/integration_openai/i/HASH` contain a hash which is kind of the key to get the real image URL in NC. To produce the link preview, NC reads the hash, gets the real image URL, gets the image and provides it as the preview. Your browser actually gets the image with a request to the NC server. I hope it's clear-ish.

PS: While I was reading the OpenAI doc again, I realized they added support for Whisper :tada: So it was quite quick to port what I did in the Replicate integration here and there we go: there's a new smart picker provider to use OpenAI's Whisper's speech-to-text transcription/translation. It would be awesome if you could try it (it's in [v1.0.3-3-nightly](https://github.com/julien-nc/integration_openai/releases/download/v1.0.3-3-nightly/integration_openai-1.0.3-3-nightly.tar.gz))

**Comment by Dual-0** [comment]
Thanks for clarification and your amazing work. Smart solution to save only the link in the DB.

Whisper Part:
The record button doesn't work. Browser permissions are given. Nginx config is straight forward as shown in the nextcloud docs.

**Comment by julien-nc** [comment]
This is not related with your webserver config. The recording completely happens in the browser. It works fine on my side with latest Firefox and Chromium.

https://user-images.githubusercontent.com/11291457/227792247-bedc3aab-6ca5-46e6-afd4-40f3d646a05c.mp4

What happens on your side when you press the record button?

**Comment by Dual-0** [comment]
The record button switches immediately its color and symbol from red back to white. Time is not running and nothing happend. I check this with chromium (Edge + Vivaldi) and on my Pixel (Vivaldi). I tested it within the notes app.

> Thanks, that was a quick test as well!
> 
> Could you check the new image generation system is also working well? It used to return the direct link to the generated image. It now returns an internal link which has a preview.

Now the previous generated image can't be loaded. (loading circle)
After a click on the loading circle its shows me this error:
```
<Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:9f915471-f01e-0050-757d-60ffe4000000 Time:2023-03-27T07:28:51.8578866Z</Message>
<AuthenticationErrorDetail>Signature not valid in the specified time frame: Start [Sat, 25 Mar 2023 17:12:35 GMT] - Expiry [Sat, 25 Mar 2023 19:12:35 GMT] - Current [Mon, 27 Mar 2023 07:28:51 GMT]</AuthenticationErrorDetail>
</Error>
```

**Comment by julien-nc** [comment]
For the recording issue, I tried on multiple OS, multiple browsers and it's always working. I don't know what's happening on your side. Any error in the browser console? We can continue this discussion in another issue if you want.

For the images not being accessible anymore, it's on the OpenAI side. They apparently delete the generated images after a few days.
