### ISSUE TITLE
Image preview don't work

### ISSUE THREAD

**Issue by JordanDIG** [julien-nc/integration_openai#3]
![image](https://user-images.githubusercontent.com/38187648/227932323-efba0557-c4d1-4013-b777-850d9660e9e2.png)

**Comment by julien-nc** [comment]
Image preview is implemented and will be included in v1.0.3. You can try it in [v1.0.3-3-nightly](https://github.com/julien-nc/integration_openai/releases/download/v1.0.3-3-nightly/integration_openai-1.0.3-3-nightly.tar.gz).

**Comment by JordanDIG** [comment]
> Image preview is implemented and will be included in v1.0.3. You can try it in [v1.0.3-3-nightly](https://github.com/julien-nc/integration_openai/releases/download/v1.0.3-3-nightly/integration_openai-1.0.3-3-nightly.tar.gz).

Thanks for you reply

**Comment by elpraga** [comment]
@julien-nc I've just installed the 1.0.3 version from the beta channel.

The link does point to a file on my server now, and after clicking it, the file is shown, bit there's still no preview in the tall chat.

Am I missing something out does talk need to be updated as well?
