### ISSUE TITLE
Strange behaviour.....truncate answer when using another language than English

### ISSUE THREAD

**Issue by crocobc** [julien-nc/integration_openai#5]
Hi there,

First thank you for this amazing app :)

I'm having a strange behaviour when using ChatGPT Text.

In notes, mail, talk same behaviour, i have truncated answer when not asking something in English 

EXAMPLE: (i'm using defaut model text-davinci-003)

```
Question: write a cover letter (English)
Answer: OK full
``` 

``` 
Question : ein Anschreiben schreiben (Deutsch)
Answer: truncate answer (around 900 -1000 caracters)
``` 

``` 
Question: ecrit une lettre de motivation (French)
Answer: truncate answer (around 900 -1000 caracters)
``` 

Is there a reason for this ? Is it linked to my free OpenAi account ?
I try to change model with no success (for gpt-turbo for example, nothing happens when clicking "Generate" button)
If i try directly from chat.openai.com it's working flawlessly..

I have no errors at all in the logs.

I'm disovering this so it may be a lack of understanding from me.

EDIT: Working flawlessly with onlyoffice plugin...with same account

Regards

**Comment by julien-nc** [comment]
This is actually because the default value for the `max_tokens` parameter was set to 300 (approx. 300 words).

v1.0.4 includes a new advanced options field to choose the max number of tokens to generate.

Thanks for the issue.
Feel free to reopen if needed.
