### ISSUE TITLE
No output after requesting service

### ISSUE THREAD

**Issue by HomemadeAdvanced** [julien-nc/integration_openai#6]
I added the app to the NC and then I added the ChatGPT API key to the NC. But when I want to test it, I write "/" in a talk group and I can select ChatGPT or Dalle. I write something in the text line and when I confirm to send it, nothing happens.

What am I doing wrong?

My DNS server resolves the ChatGPT API domain, but the ChatGPT API web page says that the key has "never" been used so far, so apparently no connection is happening.

**Comment by julien-nc** [comment]
Hi,
When you say "nothing happens", is there really nothing happening?

* Is the picker closing itself after you click the "generate" button?
* Do you see any error in the browser console log? (F12 -> console tab)
* Do you see any line mentioning `integration_openai` in the server logs (nextcloud.log)?
* Would you be ready to share this API key with me and invalidate/revoke it after I had the chance to try it?

**Comment by HomemadeAdvanced** [comment]
- Thanks for your fast response
- No the picker is not closing itself after clicking the button. There is a short loading screen on the button but nothing happens after that
- There are two errors in the console log:
xhr.js:220          POST https://examplecloud.com/apps/integration_openai/completions 400

OpenAI completions request error ChatGptCustomPickerElement.vue:211  i {message: 'Request failed with status code 400', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}

(...) "app":"integration_openai","method":"POST","url":"/apps/integration_openai/completions","message":"OpenAI API error : Client error: `POST https://api.openai.com/v1/completions` resulted in a `429 Too Many Requests` response:\n{\n    \"error\": {\n        \"message\": \"You exceeded your current quota, please check your plan and billing details.\",\n     (truncated...)\n" (...)
- I don't do something like this in general

I think it is because of the free plan I use. Because of what the NC log says I think I cannot use it with the API. The free plan browser version works for me. Kind of strange.

**Comment by julien-nc** [comment]
Thanks for the feedback. The next release will display more meaningful errors from the API responses.

What you get means you either ran out of credit or your free trial has expired. You can check that there: https://platform.openai.com/account/usage

> The free plan browser version works for me.

What do you mean?
Using ChatGPT from the OpenAI web interface does not require a valid API key.
This integration uses their REST API which require to have credit and  non-expired plan.

**Comment by julien-nc** [comment]
v1.0.4 is out.

Feel free to reopen if needed.

**Comment by Nortrix0** [comment]
I'm having the same issue, only for text generation.  I'm not over the limits, but I am getting these warnings for every character I type or button I press

NcButton.js:2 You need to fill either the text or the ariaLabel props in the button component. {text: undefined, ariaLabel: null}ariaLabel: nulltext: undefined[[Prototype]]: Object o {_uid: 385, _isVue: true, __v_skip: true, _scope: e, $options: {…}, …}

**Comment by Nortrix0** [comment]
It does look like trying it in a new .md file does work

**Comment by julien-nc** [comment]
The warning triggered by the NcButton component is not related (and should not be triggered as the button text is defined...).

Switching to another file with Text should not have any effect either.

IMO this is more about OpenAI being sometimes overloaded and returning empty responses.

It would be interesting to know the content of the network response of the POST request made to `apps/integration_openai/completions` (triggered when you click the "Generate"button) when it fails.

**Comment by Nortrix0** [comment]
Yes, it should be unrelated, but when doing DALL-E, which always worked, it did not spew those errors

But this is the POST of the apps/integration_openai/completions
<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(232, 234, 237); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size) !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" title="webpack:///integration_openai/node_modules/axios/lib/adapters/xhr.js:220" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">xhr.js:220</span> <devtools-request-link-icon class="resource-links" style="display: inline-block; white-space: nowrap; color: inherit; font-size: inherit; font-family: inherit; box-sizing: border-box; min-width: 0px; min-height: 0px; vertical-align: bottom;"><span tabindex="0" class=" link " style="cursor: pointer;"><devtools-icon title="Click to open the network panel and show request for URL: https://nextcloud/apps/integration_openai/completions" style="display: inline-block; white-space: nowrap; vertical-align: middle;"><div class="icon-basic" style="width: 16px; height: 16px; display: block; -webkit-mask-image: url(&quot;devtools://devtools/bundled/devtools-frontend/front_end/Images/network_panel_icon.svg&quot;); -webkit-mask-position: center center; -webkit-mask-repeat: no-repeat; -webkit-mask-size: 99%; background-color: var(--icon-color, var(--color-link));"></div></devtools-icon></span></devtools-request-link-icon> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-error-text-color) !important;">POST <span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-link-color); text-decoration: underline; outline-offset: 2px; cursor: pointer; word-break: break-all;">https://nextcloud/apps/integration_openai/completions</span> 400</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(232, 234, 237); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size:12px; --monospace-font-family:consolas,lucida console,courier new,monospace; --source-code-font-size:12px; --source-code-font-family:consolas,lucida console,courier new,monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size) !important;">

  | (anonymous) | @ | xhr.js:220
-- | -- | -- | --
  | e.exports | @ | xhr.js:16
  | e.exports | @ | dispatchRequest.js:56
  | d.request | @ | Axios.js:109
  | (anonymous) | @ | Axios.js:144
  | (anonymous) | @ | bind.js:9
  | onInputEnter | @ | ChatGptCustomPickerElement.vue:246
  | En | @ | vue.runtime.esm.js:3017
  | n | @ | vue.runtime.esm.js:1815
  | click | @ | NcButton.js:2
  | En | @ | vue.runtime.esm.js:3017
  | n | @ | vue.runtime.esm.js:1815
  | a._wrapper | @ | vue.runtime.esm.js:7473

</span></div>
</body>
</html>

**Comment by julien-nc** [comment]
Thanks for the feedback.

I need the response content. 
You can get it in the network tab of the browser dev tools. Select the mentioned request and then check the content of the "response" tab on the right side.

**Comment by Nortrix0** [comment]
Request URL: https://nextcloud/apps/integration_openai/completions
Request Method: POST
Status Code: 400 
Remote Address: 45.27.82.162:443
Referrer Policy: no-referrer
alt-svc: h3=":443"; ma=2592000
cache-control: no-cache, no-store, must-revalidate
content-length: 207
content-security-policy: default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'
content-type: application/json; charset=utf-8
date: Mon, 10 Apr 2023 17:38:26 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
feature-policy: autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
pragma: no-cache
referrer-policy: no-referrer
server: Caddy
server: Apache/2.4.56 (Debian)
strict-transport-security: max-age=31536000;
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-powered-by: PHP/8.1.17
x-request-id: IrMfWooKjhdYOGugnaTD
x-robots-tag: noindex, nofollow
x-xss-protection: 1; mode=block
:authority: nextcloud
:method: POST
:path: /apps/integration_openai/completions
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
content-length: 115
content-type: application/json
cookie: nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; nc_username=nortrix0; oc_sessionPassphrase=Dc71oQQkwcrFA%2B7NYX8cK5XhuizYNvRsZILqn3MRobfv4VZSNlrSGf67Tm0rhMIqRh196O0qSM9boPwR7GgunAKdmiVYC2RsCTdA56Ey4XeKYx8Z9dOiHduJszWxhliG; oc8o7h6e132r=e0f086c87df894676cd4983fd2c91585; nc_token=ka%2BViLrTrimiA9Un0fT5UjkBq2CdNjzl; nc_session_id=e0f086c87df894676cd4983fd2c91585
dnt: 1
origin: https://nextcloud
requesttoken: 9tnD5ouAMRzp5G8D5hNDSFagfLeKqbYGk1xCRm/xs3I=:saym0t6rdUawgF5UjVIQITzTEOXQ4fVAxTsKJDXe9Tc=
sec-ch-ua: "Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36





Payload was:
{prompt: "Give me the full story of the events of assassins creed", n: 1, maxTokens: 1000,…}
maxTokens
: 
1000
model
: 
"gpt-3.5-turbo"
n
: 
1
prompt
: 
"Give me the full story of the events of assassins creed"

**Comment by julien-nc** [comment]
This is the content of the "headers" tab. I need the response one.

**Comment by Nortrix0** [comment]
Oh, sorry, having to speed read at work.

{"error":"cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html) for https:\/\/api.openai.com\/v1\/chat\/completions"}
