### ISSUE TITLE
Sending Basic Requests causes  API Error

### ISSUE THREAD

**Issue by HB9HIL** [julien-nc/integration_openai#8]
Sending Basic Requests like causes an Error Popup "OpenAI error: Unknown OpenAI API error".

**Some Requests work, some do not.** 

API Key is set and correct.

Error log:

`OpenAI API error : cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.openai.com/v1/chat/completions`

NC Version 26.0.0
App Version 1.0.4
Using Model gpt-3.5-turbo

**Comment by julien-nc** [comment]
Thanks for the issue. The timeout is reached because OpenAI does not respond.

The timeout parameter will be increased to 60 seconds in the next release. Not much we can do on the Nextcloud side. The remote service is overloaded :grin:.
